### PR TITLE
Add SMIME-CAP to ASN.1

### PR DESCRIPTION
**Pull request by danvangeest**

### CODE REVIEW

**Review by fluppe2 — APPROVED** [review]
LGTM

**Comment by seanturner** [comment]
@danvangeest whoops that was a little forward, meant to do that as a suggestion not a merge.

**Comment by danvangeest** [comment]
> @danvangeest whoops that was a little forward, meant to do that as a suggestion not a merge.

no problem.

@seanturner do you have an opinion on whether the SMIME caps should be included for HashSLH-DSA.  Panos says no, Russ says it would be future-proofing to do so: https://mailarchive.ietf.org/arch/msg/spasm/Bh49ZHyIw1EdOkqFIGKXiAVzUeY/

**Comment by seanturner** [comment]
So, I tend to think that they might not be needed, but if it does turn out that a cow did jump over the moon nobody is going to be motivated enough to write a draft that just adds SMIME-CAPS.  I'd say just include it.

**Pull request merged**
